### ISSUE TITLE
Ant animation does not support in IE browser.

### ISSUE THREAD

**Issue by tmh12345** [rubenspgcavalcante/leaflet-ant-path#71] opened 2019-01-02 08:49 UTC
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: Window 10
 - Browser: IE version 11
 - Library Version: Leaflet [1.3.1], leaflet-ant-path version 2.5.6(more latest version)

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
[ Hi, I found that IE browser don't support antpath.js. The ant path animation do not work. May I know any solutions i can make for this bug?]

**Comment by rubenspgcavalcante** [comment] 2019-01-02 09:15
Hi!
Closing this because it's a duplicate of #46

**Comment by rubenspgcavalcante** [comment] 2019-01-02 13:30
Hey, can you add to the issue more information? Like the version of IE and the lib version.

**Comment by tmh12345** [comment] 2019-01-02 14:15
@rubenspgcavalcante added the version of ie and the library i use any other info u need?

**Comment by tmh12345** [comment] 2019-01-03 01:11
@rubenspgcavalcante if find out any solution we discuss here ya thank you.

**Comment by rubenspgcavalcante** [comment] 2019-01-03 10:18
Hi @tmh12345,
CSS transitions over SVGs aren't supported on IE11, and only on Edge builds over version 10240.
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/csstransitionsforsvgelements/

As Leaflet essentially works over SVGs, I can't fix as it is a Browser incompatibility, sorry about that. Although this is a good think to add on the documentation too.
I'll close this issue and open another about adding browser compatibility information on the docs.

**Closed by rubenspgcavalcante** 2019-01-03 10:18 UTC
Labels: bug

**Comment by abdulk1** [comment] 2019-02-08 21:53
@tmh12345 @rubenspgcavalcante Isn't it possible to add the same svg transitions through javascript? 

![ie_svg](https://user-images.githubusercontent.com/27826168/52508275-03dd5f00-2bc2-11e9-9551-421dbabdccdf.PNG)
